# coding: utf-8

"""
    Blockmate

    Blockmate API OpenAPI documentation  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from blockmate import schemas  # noqa: F401


class AddressRiskReport(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    AddressRiskReport
    """


    class MetaOapg:
        required = {
            "chain",
            "address",
            "details",
            "risk",
        }
        
        class properties:
            address = schemas.StrSchema
            chain = schemas.StrSchema
            
            
            class risk(
                schemas.IntSchema
            ):
                pass
            
            
            class details(
                schemas.DictSchema
            ):
            
            
                class MetaOapg:
                    
                    class properties:
                        
                        
                        class own_categories(
                            schemas.ListSchema
                        ):
                        
                        
                            class MetaOapg:
                                
                                @staticmethod
                                def items() -> typing.Type['RiskReportCategory']:
                                    return RiskReportCategory
                        
                            def __new__(
                                cls,
                                arg: typing.Union[typing.Tuple['RiskReportCategory'], typing.List['RiskReportCategory']],
                                _configuration: typing.Optional[schemas.Configuration] = None,
                            ) -> 'own_categories':
                                return super().__new__(
                                    cls,
                                    arg,
                                    _configuration=_configuration,
                                )
                        
                            def __getitem__(self, i: int) -> 'RiskReportCategory':
                                return super().__getitem__(i)
                        
                        
                        class source_of_funds_categories(
                            schemas.ListSchema
                        ):
                        
                        
                            class MetaOapg:
                                
                                @staticmethod
                                def items() -> typing.Type['RiskReportCategory']:
                                    return RiskReportCategory
                        
                            def __new__(
                                cls,
                                arg: typing.Union[typing.Tuple['RiskReportCategory'], typing.List['RiskReportCategory']],
                                _configuration: typing.Optional[schemas.Configuration] = None,
                            ) -> 'source_of_funds_categories':
                                return super().__new__(
                                    cls,
                                    arg,
                                    _configuration=_configuration,
                                )
                        
                            def __getitem__(self, i: int) -> 'RiskReportCategory':
                                return super().__getitem__(i)
                        __annotations__ = {
                            "own_categories": own_categories,
                            "source_of_funds_categories": source_of_funds_categories,
                        }
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["own_categories"]) -> MetaOapg.properties.own_categories: ...
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["source_of_funds_categories"]) -> MetaOapg.properties.source_of_funds_categories: ...
                
                @typing.overload
                def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                
                def __getitem__(self, name: typing.Union[typing_extensions.Literal["own_categories", "source_of_funds_categories", ], str]):
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["own_categories"]) -> typing.Union[MetaOapg.properties.own_categories, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["source_of_funds_categories"]) -> typing.Union[MetaOapg.properties.source_of_funds_categories, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                
                def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["own_categories", "source_of_funds_categories", ], str]):
                    return super().get_item_oapg(name)
                
            
                def __new__(
                    cls,
                    *args: typing.Union[dict, frozendict.frozendict, ],
                    own_categories: typing.Union[MetaOapg.properties.own_categories, list, tuple, schemas.Unset] = schemas.unset,
                    source_of_funds_categories: typing.Union[MetaOapg.properties.source_of_funds_categories, list, tuple, schemas.Unset] = schemas.unset,
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                ) -> 'details':
                    return super().__new__(
                        cls,
                        *args,
                        own_categories=own_categories,
                        source_of_funds_categories=source_of_funds_categories,
                        _configuration=_configuration,
                        **kwargs,
                    )
            case_id = schemas.StrSchema
            request_datetime = schemas.StrSchema
            response_datetime = schemas.StrSchema
            __annotations__ = {
                "address": address,
                "chain": chain,
                "risk": risk,
                "details": details,
                "case_id": case_id,
                "request_datetime": request_datetime,
                "response_datetime": response_datetime,
            }
    
    chain: MetaOapg.properties.chain
    address: MetaOapg.properties.address
    details: MetaOapg.properties.details
    risk: MetaOapg.properties.risk
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["address"]) -> MetaOapg.properties.address: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["chain"]) -> MetaOapg.properties.chain: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["risk"]) -> MetaOapg.properties.risk: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["details"]) -> MetaOapg.properties.details: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["case_id"]) -> MetaOapg.properties.case_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["request_datetime"]) -> MetaOapg.properties.request_datetime: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["response_datetime"]) -> MetaOapg.properties.response_datetime: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["address", "chain", "risk", "details", "case_id", "request_datetime", "response_datetime", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["address"]) -> MetaOapg.properties.address: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["chain"]) -> MetaOapg.properties.chain: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["risk"]) -> MetaOapg.properties.risk: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["details"]) -> MetaOapg.properties.details: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["case_id"]) -> typing.Union[MetaOapg.properties.case_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["request_datetime"]) -> typing.Union[MetaOapg.properties.request_datetime, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["response_datetime"]) -> typing.Union[MetaOapg.properties.response_datetime, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["address", "chain", "risk", "details", "case_id", "request_datetime", "response_datetime", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        chain: typing.Union[MetaOapg.properties.chain, str, ],
        address: typing.Union[MetaOapg.properties.address, str, ],
        details: typing.Union[MetaOapg.properties.details, dict, frozendict.frozendict, ],
        risk: typing.Union[MetaOapg.properties.risk, decimal.Decimal, int, ],
        case_id: typing.Union[MetaOapg.properties.case_id, str, schemas.Unset] = schemas.unset,
        request_datetime: typing.Union[MetaOapg.properties.request_datetime, str, schemas.Unset] = schemas.unset,
        response_datetime: typing.Union[MetaOapg.properties.response_datetime, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'AddressRiskReport':
        return super().__new__(
            cls,
            *args,
            chain=chain,
            address=address,
            details=details,
            risk=risk,
            case_id=case_id,
            request_datetime=request_datetime,
            response_datetime=response_datetime,
            _configuration=_configuration,
            **kwargs,
        )

from blockmate.model.risk_report_category import RiskReportCategory
