# coding: utf-8

# flake8: noqa

"""
    Blockmate

    Blockmate API OpenAPI documentation  # noqa: E501

    The version of the OpenAPI document: 0.0.2
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from blockmate.api_client import ApiClient

# import Configuration
from blockmate.configuration import Configuration

# import exceptions
from blockmate.exceptions import OpenApiException
from blockmate.exceptions import ApiAttributeError
from blockmate.exceptions import ApiTypeError
from blockmate.exceptions import ApiValueError
from blockmate.exceptions import ApiKeyError
from blockmate.exceptions import ApiException
