# coding: utf-8

"""
    Blockmate

    Blockmate API OpenAPI documentation  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

from blockmate.paths.v1_addressname_multi.post import GetAddressNameInfoMulti
from blockmate.paths.v1_addressname_simple.get import GetAddressNameInfoSingle


class AddressNameAndCategoryInfoApi(
    GetAddressNameInfoMulti,
    GetAddressNameInfoSingle,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
