# coding: utf-8

"""
    Blockmate

    Blockmate API OpenAPI documentation  # noqa: E501

    The version of the OpenAPI document: 0.0.2
    Generated by: https://openapi-generator.tech
"""

from blockmate.paths.v1_ens_address_from_domain.get import GetAddressFromDomain
from blockmate.paths.v1_ens_domain_from_address.get import GetDomainFromAddress


class ENSApi(
    GetAddressFromDomain,
    GetDomainFromAddress,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
