# coding: utf-8

"""
    Blockmate

    Blockmate API OpenAPI documentation  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

from blockmate.paths.v1_exchangerate_current.get import GetCurrentExchangeRate
from blockmate.paths.v1_exchangerate_history.get import GetHistoricalExchangeRate


class ExchangeRateInfoApi(
    GetCurrentExchangeRate,
    GetHistoricalExchangeRate,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
