# coding: utf-8

"""
    Blockmate

    Blockmate API OpenAPI documentation  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""

from blockmate.paths.v1_risk_score.get import GetAddressRiskScore
from blockmate.paths.v1_risk_score_details_case_id.get import GetAddressRiskScoreCase
from blockmate.paths.v1_risk_score_details.get import GetAddressRiskScoreDetails
from blockmate.paths.v1_risk_transaction_score.get import GetTransactionRiskScore
from blockmate.paths.v1_risk_transaction_score_details_case_id.get import GetTransactionRiskScoreCase
from blockmate.paths.v1_risk_transaction_score_details.get import GetTransactionRiskScoreDetails


class RiskInfoApi(
    GetAddressRiskScore,
    GetAddressRiskScoreCase,
    GetAddressRiskScoreDetails,
    GetTransactionRiskScore,
    GetTransactionRiskScoreCase,
    GetTransactionRiskScoreDetails,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
