# coding: utf-8

"""
    Blockmate

    Blockmate API OpenAPI documentation  # noqa: E501

    The version of the OpenAPI document: 0.0.2
    Generated by: https://openapi-generator.tech
"""

from blockmate.paths.v1_account_provider_connect.post import ConnectAccount
from blockmate.paths.v1_account_provider_account_account_id.delete import DeleteAccount
from blockmate.paths.v1_account_provider_connect.get import GetAccountHint


class UserAccountManagementApi(
    ConnectAccount,
    DeleteAccount,
    GetAccountHint,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
