# coding: utf-8

"""
    Blockmate

    Blockmate API OpenAPI documentation  # noqa: E501

    The version of the OpenAPI document: 0.0.2
    Generated by: https://openapi-generator.tech
"""

from blockmate.paths.v1_users_id_auth.get import AuthUser
from blockmate.paths.v1_users.post import CreateUser
from blockmate.paths.v1_users_id.delete import DeleteUser
from blockmate.paths.v1_users_id.get import GetUser
from blockmate.paths.v1_users.get import ListUsers
from blockmate.paths.v1_users_id.post import UpdateUser


class UserManagementApi(
    AuthUser,
    CreateUser,
    DeleteUser,
    GetUser,
    ListUsers,
    UpdateUser,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
